from datetime import datetime, time, timedelta, timezone
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from sqlalchemy import insert, select
from sqlalchemy.orm import Session

from app.models import Garden, Plant, Reminder, TelegramAccount, User, UserNotification
from app.services.seasonal_service import seasonal_calendar_items
from app.services.telegram_service import TelegramServiceError, send_message
from app.services.weather_service import WeatherServiceError, weather_service


def _aware(value: datetime) -> datetime:
    return value.replace(tzinfo=timezone.utc) if value.tzinfo is None else value


_KEY_LOOKUP_CHUNK = 500


def _add(
    pending: list[dict],
    seen: set[str],
    *,
    user_id: int,
    kind: str,
    title: str,
    body: str,
    event_at: datetime,
    key: str,
    delivery_channel: str = "both",
) -> bool:
    """Stage one notification, skipping duplicates generated by this run."""
    if key in seen:
        return False
    seen.add(key)
    pending.append({
        "user_id": user_id,
        "kind": kind,
        "title": title,
        "body": body,
        "event_at": _aware(event_at).astimezone(timezone.utc),
        "deduplication_key": key,
        "delivery_channel": delivery_channel,
    })
    return True


def _persisted_keys(db: Session, keys: set[str]) -> set[str]:
    """Check only the candidate keys instead of loading the whole table."""
    persisted: set[str] = set()
    candidates = list(keys)
    for start in range(0, len(candidates), _KEY_LOOKUP_CHUNK):
        batch = candidates[start:start + _KEY_LOOKUP_CHUNK]
        persisted.update(db.scalars(
            select(UserNotification.deduplication_key).where(
                UserNotification.deduplication_key.in_(batch)
            )
        ))
    return persisted


def _insert_notifications(db: Session, rows: list[dict]) -> int:
    """Insert staged notifications, tolerating duplicates from a concurrent run."""
    if not rows:
        return 0
    statement = insert(UserNotification).values(rows)
    if db.bind is not None and db.bind.dialect.name == "postgresql":
        statement = statement.on_conflict_do_nothing(
            index_elements=["deduplication_key"]
        )
    else:
        statement = statement.prefix_with("OR IGNORE")
    return int(db.execute(statement).rowcount or 0)


def generate_due_notifications(
    db: Session,
    *,
    now: datetime | None = None,
    include_weather: bool = True,
) -> int:
    now = _aware(now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    end = now + timedelta(hours=24)
    pending: list[dict] = []
    seen: set[str] = set()

    reminder_rows = db.execute(
        select(Reminder, Plant, User)
        .join(Plant, Plant.id == Reminder.plant_id)
        .join(Garden, Garden.id == Plant.garden_id)
        .join(User, User.id == Garden.user_id)
        .where(Reminder.completed_at.is_(None), Reminder.due_at >= now, Reminder.due_at < end)
    ).all()
    for reminder, plant, user in reminder_rows:
        language = user.language if user.language in {"ru", "lv", "en"} else "ru"
        title = {"ru": "Скоро задача по уходу", "lv": "Drīz kopšanas uzdevums", "en": "Care task due soon"}[language]
        body = {
            "ru": f"{plant.name}: {reminder.title}",
            "lv": f"{plant.name}: {reminder.title}",
            "en": f"{plant.name}: {reminder.title}",
        }[language]
        _add(pending, seen, user_id=user.id, kind="reminder", title=title, body=body,
                        event_at=_aware(reminder.due_at), key=f"reminder:{reminder.id}",
                        delivery_channel=reminder.preferred_channel)

    users = list(db.scalars(select(User).order_by(User.id)))
    for user in users:
        gardens = list(db.scalars(select(Garden).where(Garden.user_id == user.id).order_by(Garden.id)))
        for item in seasonal_calendar_items(gardens, user, now, end):
            _add(
                pending, seen, user_id=user.id, kind="seasonal_task", title=item["title"],
                body=f"{item['garden_name']}: {item['description']}", event_at=item["starts_at"],
                key=str(item["reference_id"]),
            )
        if not include_weather:
            continue
        for garden in gardens[:20]:
            location = garden.location or user.region
            if not location:
                continue
            try:
                forecast = weather_service.get_forecast(location, user.language)
            except WeatherServiceError:
                continue
            try:
                zone = ZoneInfo(forecast.timezone)
            except ZoneInfoNotFoundError:
                zone = timezone.utc
            for warning in forecast.warnings:
                event_at = datetime.combine(warning.date, time(hour=9), tzinfo=zone).astimezone(timezone.utc)
                if now <= event_at < end:
                    _add(
                        pending, seen, user_id=user.id, kind="weather_warning", title=warning.title,
                        body=f"{garden.name}: {warning.advice}", event_at=event_at,
                        key=f"weather:{garden.id}:{warning.date}:{warning.kind}",
                    )
    persisted = _persisted_keys(db, seen)
    created = _insert_notifications(
        db,
        [row for row in pending if row["deduplication_key"] not in persisted],
    )
    db.commit()
    return created


def deliver_pending_telegram_notifications(db: Session, *, now: datetime | None = None) -> tuple[int, int]:
    now = _aware(now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    rows = db.execute(
        select(UserNotification, TelegramAccount)
        .join(TelegramAccount, TelegramAccount.user_id == UserNotification.user_id)
        .where(
            TelegramAccount.active.is_(True),
            UserNotification.telegram_sent_at.is_(None),
            UserNotification.event_at < now + timedelta(hours=24),
            UserNotification.delivery_attempts < 5,
            UserNotification.delivery_channel.in_(("telegram", "both")),
        )
        .order_by(UserNotification.created_at)
        .limit(200)
    ).all()
    sent = failed = 0
    for notification, account in rows:
        notification.delivery_attempts += 1
        try:
            send_message(account.chat_id, f"{notification.title}\n{notification.body}")
        except TelegramServiceError as exc:
            notification.last_delivery_error = str(exc)[:300]
            failed += 1
        else:
            notification.telegram_sent_at = now
            notification.last_delivery_error = None
            sent += 1
    db.commit()
    return sent, failed
